/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encrypter */

#ifndef _Included_Encrypter
#define _Included_Encrypter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encrypter
 * Method:    encryptInC
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_Encrypter_encryptInC
  (JNIEnv *, jobject, jbyteArray, jlongArray);

/*
 * Class:     Encrypter
 * Method:    decryptInC
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_Encrypter_decryptInC
  (JNIEnv *, jobject, jbyteArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
